version: 1.0.{build}

branches:
  only:
  - master

before_build:
- ps: nuget restore TeacherDiary.sln

build:
  project: TeacherDiary.sln
  verbosity: minimal

environment:
  COVERALLS_REPO_TOKEN:
    secure: SELaNW6kHltFIYpeXRDo/Mh+BLHYsJfZflVI3cp7AiY1I/XNrBTZhCWWMSIN+ukJ 

after_test: 
  - packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -filter:"+[*]* -[*]*ViewModel -[*]*Config" -target:"packages\NUnit.ConsoleRunner.3.6.1\tools\nunit3-console.exe" -targetargs:"/domain:single   
    test\TeacherDiary.Clients.Mvc.Tests\bin\Debug\TeacherDiary.Clients.Mvc.Tests.dll" -output:coverage.xml

  - packages\coveralls.io.1.3.4\tools\coveralls.net.exe --opencover coverage.xml 
